<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <RootNamespace>FatteningFarmerFramework</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GamePath>/mnt/greenstorage/Green Games/Steam/steamapps/common/Stardew Valley/</GamePath>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
      <PackageReference Include="System.CodeDom" Version="8.0.0" />
    </ItemGroup>
</Project>
